//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 18/12/2019 03:27:23
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace Data.Models
{
    [Serializable()]
    public partial class EmpData : INotifyPropertyChanging, INotifyPropertyChanged, ICloneable
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);

        private int _ID;

        private string _Code;

        private string _FirstName;

        private string _LastName;

        private bool _Gender;

        private string _JobTitle;

        private int _DepartmentID;

        private string _DepartmentName;

        public EmpData()
        {
            OnCreated();
        }

        [System.ComponentModel.DataAnnotations.Range(typeof(int), @"1", @"5", ErrorMessage = @"Range Error")]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = @"Field Required")]
        public virtual int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                if (this._ID != value)
                {
                    this.OnIDChanging(value);
                    this.SendPropertyChanging("ID");
                    this._ID = value;
                    this.SendPropertyChanged("ID");
                    this.OnIDChanged();
                }
            }
        }

        [System.ComponentModel.DataAnnotations.StringLength(32, ErrorMessage = @"Length Error")]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = @"Field Required")]
        public virtual string Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                if (this._Code != value)
                {
                    this.OnCodeChanging(value);
                    this.SendPropertyChanging("Code");
                    this._Code = value;
                    this.SendPropertyChanged("Code");
                    this.OnCodeChanged();
                }
            }
        }

        [System.ComponentModel.DataAnnotations.StringLength(64, ErrorMessage = @"Length Error")]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = @"Field Required")]
        public virtual string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                if (this._FirstName != value)
                {
                    this.OnFirstNameChanging(value);
                    this.SendPropertyChanging("FirstName");
                    this._FirstName = value;
                    this.SendPropertyChanged("FirstName");
                    this.OnFirstNameChanged();
                }
            }
        }

        [System.ComponentModel.DataAnnotations.StringLength(64, ErrorMessage = @"Length Error")]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = @"Field Required")]
        public virtual string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                if (this._LastName != value)
                {
                    this.OnLastNameChanging(value);
                    this.SendPropertyChanging("LastName");
                    this._LastName = value;
                    this.SendPropertyChanged("LastName");
                    this.OnLastNameChanged();
                }
            }
        }

        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = @"Field Required")]
        public virtual bool Gender
        {
            get
            {
                return this._Gender;
            }
            set
            {
                if (this._Gender != value)
                {
                    this.OnGenderChanging(value);
                    this.SendPropertyChanging("Gender");
                    this._Gender = value;
                    this.SendPropertyChanged("Gender");
                    this.OnGenderChanged();
                }
            }
        }

        [System.ComponentModel.DataAnnotations.StringLength(64, ErrorMessage = @"Length Error")]
        public virtual string JobTitle
        {
            get
            {
                return this._JobTitle;
            }
            set
            {
                if (this._JobTitle != value)
                {
                    this.OnJobTitleChanging(value);
                    this.SendPropertyChanging("JobTitle");
                    this._JobTitle = value;
                    this.SendPropertyChanged("JobTitle");
                    this.OnJobTitleChanged();
                }
            }
        }

        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = @"Field Required")]
        public virtual int DepartmentID
        {
            get
            {
                return this._DepartmentID;
            }
            set
            {
                if (this._DepartmentID != value)
                {
                    this.OnDepartmentIDChanging(value);
                    this.SendPropertyChanging("DepartmentID");
                    this._DepartmentID = value;
                    this.SendPropertyChanged("DepartmentID");
                    this.OnDepartmentIDChanged();
                }
            }
        }

        [System.ComponentModel.DataAnnotations.StringLength(64, ErrorMessage = @"Length Error")]
        [System.ComponentModel.DataAnnotations.Required(ErrorMessage = @"Field Required")]
        public virtual string DepartmentName
        {
            get
            {
                return this._DepartmentName;
            }
            set
            {
                if (this._DepartmentName != value)
                {
                    this.OnDepartmentNameChanging(value);
                    this.SendPropertyChanging("DepartmentName");
                    this._DepartmentName = value;
                    this.SendPropertyChanged("DepartmentName");
                    this.OnDepartmentNameChanged();
                }
            }
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
            EmpData toCompare = obj as EmpData;
            if (toCompare == null)
            {
                return false;
            }

            if (!Object.Equals(this.ID, toCompare.ID))
                return false;
            if (!Object.Equals(this.Code, toCompare.Code))
                return false;
            if (!Object.Equals(this.FirstName, toCompare.FirstName))
                return false;
            if (!Object.Equals(this.LastName, toCompare.LastName))
                return false;
            if (!Object.Equals(this.Gender, toCompare.Gender))
                return false;
            if (!Object.Equals(this.JobTitle, toCompare.JobTitle))
                return false;
            if (!Object.Equals(this.DepartmentID, toCompare.DepartmentID))
                return false;
            if (!Object.Equals(this.DepartmentName, toCompare.DepartmentName))
                return false;

            return true;
        }

        public override int GetHashCode()
        {
            int hashCode = 13;
            hashCode = (hashCode * 7) + ID.GetHashCode();
            hashCode = (hashCode * 7) + Code.GetHashCode();
            hashCode = (hashCode * 7) + FirstName.GetHashCode();
            hashCode = (hashCode * 7) + LastName.GetHashCode();
            hashCode = (hashCode * 7) + Gender.GetHashCode();
            hashCode = (hashCode * 7) + DepartmentID.GetHashCode();
            hashCode = (hashCode * 7) + DepartmentName.GetHashCode();
            return hashCode;
        }
        partial void OnIDChanging(int value);

        partial void OnIDChanged();
        partial void OnCodeChanging(string value);

        partial void OnCodeChanged();
        partial void OnFirstNameChanging(string value);

        partial void OnFirstNameChanged();
        partial void OnLastNameChanging(string value);

        partial void OnLastNameChanged();
        partial void OnGenderChanging(bool value);

        partial void OnGenderChanged();
        partial void OnJobTitleChanging(string value);

        partial void OnJobTitleChanged();
        partial void OnDepartmentIDChanging(int value);

        partial void OnDepartmentIDChanged();
        partial void OnDepartmentNameChanging(string value);

        partial void OnDepartmentNameChanged();

        #endregion

        #region ICloneable Members

        public virtual object Clone()
        {
            EmpData obj = new EmpData();
            obj.ID = ID;
            obj.Code = Code;
            obj.FirstName = FirstName;
            obj.LastName = LastName;
            obj.Gender = Gender;
            obj.JobTitle = JobTitle;
            obj.DepartmentID = DepartmentID;
            obj.DepartmentName = DepartmentName;
            return obj;
        }

        #endregion

        public virtual event PropertyChangingEventHandler PropertyChanging;

        public virtual event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName)
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
